apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: swimlane-app-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels: { app: swimlane-app }
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.namespace }}
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: data
      podSelector:
        matchLabels:
          app.kubernetes.io/name: mongodb
    ports:
    - protocol: TCP
      port: 27017
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 443
