apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: swimlane-app-allow-mongo
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels: { app: swimlane-app }
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: data
      podSelector:
        matchLabels:
          app.kubernetes.io/name: mongodb
    ports:
    - protocol: TCP
      port: 27017
  policyTypes: ["Egress"]
