apiVersion: v1
kind: ServiceAccount
metadata:
  name: swimlane-app
  namespace: {{ .Values.namespace }}
  labels:
    app: swimlane-app
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: swimlane-app
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: swimlane-app
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: swimlane-app
subjects:
- kind: ServiceAccount
  name: swimlane-app
  namespace: {{ .Values.namespace }}
