apiVersion: v1
kind: Service
metadata:
  name: swimlane-app
  namespace: {{ .Values.namespace }}
spec:
  selector: { app: swimlane-app }
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3000
    protocol: TCP
  type: {{ .Values.service.type }}
