namespace: apps
replicaCount: 2

image:
  repository: "<ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/devops-practical"
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  port: 3000
  type: LoadBalancer

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60

pdb:
  enabled: true
  minAvailable: 1

envFromSecret: "app-conn"
